---
name: Bug Report
description: Report a bug or unexpected behavior
title: "bug: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide information about your environment:
        - Browser: [e.g. Chrome 120.0]
        - OS: [e.g. macOS 14.0]
        - Node version (if applicable): [e.g. 20.0.0]
        - Any other relevant details

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional context, screenshots, or error messages
      placeholder: Add any other context about the problem here.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please check all that apply
      options:
        - label: I have searched for existing issues
          required: true
        - label: I have provided all requested information
        - label: I am willing to help fix this issue
