---
name: Feature Request
description: Suggest a new feature or enhancement
title: "feat: "
labels: ["enhancement"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief description of the proposed feature
      placeholder: What would you like to see added?
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem/Use Case
      description: What problem does this solve or what use case does it address?
      placeholder: |
        Describe the current limitation or pain point.
        Why is this feature needed?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: |
        Describe the implementation approach.
        Any technical considerations?
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Nice to have
        - Should have
        - Must have
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: Other ways to solve this problem?

  - type: checkboxes
    id: checklist
    attributes:
      label: Additional Information
      options:
        - label: I am willing to help implement this feature
        - label: This feature aligns with Silicon Soap's mission
        - label: I have checked for existing similar requests
