// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.28.0";

// src/lib/mcp/tools/create-debate.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z } from "npm:zod@^4.5.4";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.84.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find(
          (v) => typeof v === "string" && v.trim().startsWith("sb_publishable_")
        )?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseAnon() {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("This tool requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function invokeFunction(ctx, name, init = {}) {
  const token = ctx.getToken();
  if (!token) throw new Error("This tool requires a verified OAuth token");
  const url = `${supabaseProjectUrl()}/functions/v1/${name}${init.path ?? ""}`;
  const res = await fetch(url, {
    method: init.method ?? "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json"
    },
    body: init.body === void 0 ? void 0 : JSON.stringify(init.body)
  });
  const text = await res.text();
  let body = text;
  try {
    body = JSON.parse(text);
  } catch {
  }
  return { status: res.status, body };
}
function ok(payload, summary) {
  return {
    content: [
      { type: "text", text: summary ?? JSON.stringify(payload, null, 2) }
    ],
    structuredContent: payload
  };
}
function fail(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function requireAuth(ctx) {
  if (!ctx.isAuthenticated()) throw new Error("Not authenticated");
  const userId = ctx.getUserId();
  if (!userId) throw new Error("No user id on token");
  return userId;
}
async function isAdmin(ctx) {
  const supabase = supabaseForUser(ctx);
  const { data, error } = await supabase.rpc("has_role", {
    _user_id: ctx.getUserId(),
    _role: "admin"
  });
  if (error) return false;
  return data === true;
}
async function logAgentAction(ctx, entry) {
  try {
    const userId = ctx.getUserId();
    if (!userId) return;
    await supabaseForUser(ctx).from("agent_activity_log").insert({
      actor_user_id: userId,
      actor_label: ctx.getUserEmail?.() ?? null,
      client_id: ctx.getClientId?.() ?? null,
      source: "mcp",
      tool_name: entry.tool_name,
      action: entry.action ?? "write",
      target_type: entry.target_type ?? null,
      target_id: entry.target_id ?? null,
      success: entry.success,
      error_message: entry.error_message ?? null,
      input: entry.input ?? {},
      result: entry.result ?? {},
      duration_ms: entry.duration_ms ?? null
    });
  } catch {
  }
}
async function audited(ctx, meta, run) {
  const startedAt = Date.now();
  try {
    const result = await run();
    const failed = result?.isError === true;
    await logAgentAction(ctx, {
      ...meta,
      success: !failed,
      error_message: failed ? "tool returned an error" : null,
      result: result?.structuredContent ?? {},
      duration_ms: Date.now() - startedAt
    });
    return result;
  } catch (err) {
    await logAgentAction(ctx, {
      ...meta,
      success: false,
      error_message: err instanceof Error ? err.message : String(err),
      duration_ms: Date.now() - startedAt
    });
    throw err;
  }
}

// src/lib/mcp/tools/create-debate.ts
var create_debate_default = defineTool({
  name: "create_debate",
  title: "Create a debate",
  description: "Queue a new multi-agent debate on SiliconSoap as the signed-in user. Costs 1 credit. Returns immediately with a debate id \u2014 poll `get_debate_status` until it is completed, then read it with `get_debate`.",
  inputSchema: {
    topic: z.string().describe("The debate topic or question (max 2000 chars)."),
    models: z.array(z.string()).describe("2 or 3 model ids from `list_models` \u2014 one per agent."),
    rounds: z.number().int().optional().describe("1-5, default 2."),
    scenario_id: z.enum(["general-problem", "ethical-dilemma", "future-prediction"]).optional(),
    personas: z.array(z.enum(["analytical", "creative", "strategic", "empathetic"])).optional().describe("One persona per agent."),
    agent_names: z.array(z.string()).optional().describe("Display names per agent."),
    response_length: z.enum(["short", "medium", "long"]).optional(),
    conversation_tone: z.enum(["formal", "casual", "heated", "collaborative"]).optional(),
    agreement_bias: z.number().int().optional().describe("0 = combative, 100 = agreeable. Default 50."),
    personality_intensity: z.enum(["mild", "moderate", "extreme"]).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: true },
  handler: async (input, ctx) => {
    requireAuth(ctx);
    if (!input.topic.trim()) return fail("`topic` cannot be empty.");
    if (input.models.length < 2 || input.models.length > 3) {
      return fail("`models` must contain 2 or 3 model ids (see `list_models`).");
    }
    return audited(
      ctx,
      {
        tool_name: "create_debate",
        action: "create",
        target_type: "debate",
        target_id: input.topic.slice(0, 120),
        input
      },
      async () => {
        const { status, body } = await invokeFunction(ctx, "debates-api", {
          method: "POST",
          path: "/debates",
          body: input
        });
        if (status >= 400) {
          const message = body?.error ?? `Debate creation failed (${status}).`;
          return fail(message);
        }
        return ok(body);
      }
    );
  }
});

// src/lib/mcp/tools/get-debate.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z2 } from "npm:zod@^4.5.4";
var get_debate_default = defineTool2({
  name: "get_debate",
  title: "Get debate transcript",
  description: "Fetch a debate and its full transcript by debate id or public share id. Signed-in callers can also read their own private debates.",
  inputSchema: {
    id: z2.string().optional().describe("Debate UUID."),
    share_id: z2.string().optional().describe("Public share id, as in /shared/<share_id>.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, share_id }, ctx) => {
    if (!id && !share_id) return fail("Provide either `id` or `share_id`.");
    const supabase = ctx.isAuthenticated() ? supabaseForUser(ctx) : supabaseAnon();
    let query = supabase.from("agent_chats").select("*").is("deleted_at", null);
    query = id ? query.eq("id", id) : query.eq("share_id", share_id);
    const { data: debate, error } = await query.maybeSingle();
    if (error) return fail(error.message);
    if (!debate) return fail("Debate not found (or not public).");
    const { data: messages, error: msgErr } = await supabase.from("agent_chat_messages").select("agent, persona, message, model, created_at").eq("chat_id", debate.id).order("created_at", { ascending: true });
    if (msgErr) return fail(msgErr.message);
    return ok({
      debate,
      messages: messages ?? [],
      status: debate.run_status ?? "completed",
      share_url: debate.share_id ? `https://siliconsoap.com/shared/${debate.share_id}` : null
    });
  }
});

// src/lib/mcp/tools/get-debate-status.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z3 } from "npm:zod@^4.5.4";
var get_debate_status_default = defineTool3({
  name: "get_debate_status",
  title: "Get debate run status",
  description: "Poll the run status of one of your debates: queued | running | completed | failed, with round progress and message count.",
  inputSchema: { id: z3.string().describe("Debate UUID returned by `create_debate`.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    const { data: chat, error } = await supabase.from("agent_chats").select(
      "id, title, run_status, run_error, run_current_round, run_total_rounds, run_started_at, run_completed_at, share_id"
    ).eq("id", id).is("deleted_at", null).maybeSingle();
    if (error) return fail(error.message);
    if (!chat) return fail("Debate not found.");
    const { count } = await supabase.from("agent_chat_messages").select("id", { count: "exact", head: true }).eq("chat_id", id);
    return ok({
      id: chat.id,
      title: chat.title,
      status: chat.run_status ?? "completed",
      error: chat.run_error,
      current_round: chat.run_current_round,
      total_rounds: chat.run_total_rounds,
      messages_so_far: count ?? 0,
      share_url: chat.share_id ? `https://siliconsoap.com/shared/${chat.share_id}` : null
    });
  }
});

// src/lib/mcp/tools/list-agent-profiles.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.28.0";
var list_agent_profiles_default = defineTool4({
  name: "list_agent_profiles",
  title: "List agent personas",
  description: "List the agent personas available for debates (system personas, plus the caller's own when signed in).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const supabase = ctx.isAuthenticated() ? supabaseForUser(ctx) : supabaseAnon();
    const { data, error } = await supabase.from("agent_profiles").select("slug, name, description, instructions, icon_name, is_system, is_premium").order("name", { ascending: true });
    if (error) return fail(error.message);
    return ok({ count: data?.length ?? 0, profiles: data ?? [] });
  }
});

// src/lib/mcp/tools/list-debates.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z4 } from "npm:zod@^4.5.4";
var list_debates_default = defineTool5({
  name: "list_debates",
  title: "List public debates",
  description: "List public SiliconSoap debates (newest or most viewed first), optionally filtered by a text search on the topic.",
  inputSchema: {
    search: z4.string().optional().describe("Free-text filter on debate title/prompt."),
    order: z4.enum(["newest", "most_viewed"]).optional().describe("Sort order. Defaults to newest."),
    limit: z4.number().int().optional().describe("1-50, default 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, order, limit }) => {
    const supabase = supabaseAnon();
    const take = Math.min(Math.max(limit ?? 20, 1), 50);
    let query = supabase.from("agent_chats").select(
      "id, title, prompt, scenario_id, settings, share_id, view_count, created_at, run_status"
    ).eq("is_public", true).is("deleted_at", null);
    if (search?.trim()) {
      const term = search.trim().replace(/[%,]/g, " ");
      query = query.or(`title.ilike.%${term}%,prompt.ilike.%${term}%`);
    }
    query = order === "most_viewed" ? query.order("view_count", { ascending: false }) : query.order("created_at", { ascending: false });
    const { data, error } = await query.limit(take);
    if (error) return fail(error.message);
    return ok({ count: data?.length ?? 0, debates: data ?? [] });
  }
});

// src/lib/mcp/tools/list-feature-flags.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.28.0";
var list_feature_flags_default = defineTool6({
  name: "list_feature_flags",
  title: "List feature flags",
  description: "List every SiliconSoap feature flag and configuration value (enabled state, text value, numeric value). This is the platform's configuration source of truth.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const { data, error } = await supabaseAnon().from("feature_flags").select("key, name, description, enabled, text_value, numeric_value, updated_at").order("key", { ascending: true });
    if (error) return fail(error.message);
    return ok({ count: data?.length ?? 0, flags: data ?? [] });
  }
});

// src/lib/mcp/tools/list-hall-of-shame.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z5 } from "npm:zod@^4.5.4";
var list_hall_of_shame_default = defineTool7({
  name: "list_hall_of_shame",
  title: "List Hall of Shame moments",
  description: "List the most dramatic extracted moments from SiliconSoap debates (quote, agent, shame type, severity).",
  inputSchema: { limit: z5.number().int().optional().describe("1-50, default 20.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const { data, error } = await supabaseAnon().from("hall_of_shame").select("agent_name, quote, context, shame_type, severity, share_id, created_at").order("created_at", { ascending: false }).limit(Math.min(Math.max(limit ?? 20, 1), 50));
    if (error) return fail(error.message);
    return ok({ count: data?.length ?? 0, moments: data ?? [] });
  }
});

// src/lib/mcp/tools/list-models.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z6 } from "npm:zod@^4.5.4";
var list_models_default = defineTool8({
  name: "list_models",
  title: "List curated models",
  description: "List the LLMs curated for SiliconSoap debates, with provider, pricing, reasoning support and whether they are enabled.",
  inputSchema: {
    include_disabled: z6.boolean().optional().describe("Include models that are currently disabled in the app.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ include_disabled }) => {
    const supabase = supabaseAnon();
    let query = supabase.from("curated_models").select(
      "model_id, display_name, provider, category, is_enabled, is_free, disable_reasoning, supports_reasoning, price_input, price_output, price_tier, speed_rating, context_window, license_type, default_for_agent, sort_order, description, pricing_updated_at"
    ).order("sort_order", { ascending: true });
    if (!include_disabled) query = query.eq("is_enabled", true);
    const { data, error } = await query;
    if (error) return fail(error.message);
    return ok({ count: data?.length ?? 0, models: data ?? [] });
  }
});

// src/lib/mcp/tools/list-my-debates.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z7 } from "npm:zod@^4.5.4";
var list_my_debates_default = defineTool9({
  name: "list_my_debates",
  title: "List my debates",
  description: "List the signed-in user's own debates, newest first.",
  inputSchema: { limit: z7.number().int().optional().describe("1-50, default 20.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    const userId = requireAuth(ctx);
    const { data, error } = await supabaseForUser(ctx).from("agent_chats").select(
      "id, title, prompt, scenario_id, share_id, is_public, view_count, run_status, created_at"
    ).eq("user_id", userId).is("deleted_at", null).order("created_at", { ascending: false }).limit(Math.min(Math.max(limit ?? 20, 1), 50));
    if (error) return fail(error.message);
    return ok({ count: data?.length ?? 0, debates: data ?? [] });
  }
});

// src/lib/mcp/tools/list-openrouter-models.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z8 } from "npm:zod@^4.5.4";
var list_openrouter_models_default = defineTool10({
  name: "list_openrouter_models",
  title: "Browse OpenRouter catalog",
  description: "Browse the live OpenRouter model catalog to discover newly released models, and see which of them are not yet curated on SiliconSoap. Use before `upsert_curated_model`.",
  inputSchema: {
    search: z8.string().optional().describe("Filter on model id or name, e.g. 'claude', 'qwen', 'free'."),
    only_new: z8.boolean().optional().describe("Only return models that are not already curated on SiliconSoap."),
    limit: z8.number().int().optional().describe("1-60, default 30.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ search, only_new, limit }) => {
    const res = await fetch("https://openrouter.ai/api/v1/models");
    if (!res.ok) return fail(`OpenRouter catalog request failed (${res.status}).`);
    const payload = await res.json();
    let models = payload.data ?? [];
    const { data: curated, error } = await supabaseAnon().from("curated_models").select("model_id");
    if (error) return fail(error.message);
    const known = new Set((curated ?? []).map((m) => m.model_id));
    const term = search?.trim().toLowerCase();
    if (term) {
      models = models.filter(
        (m) => m.id.toLowerCase().includes(term) || (m.name ?? "").toLowerCase().includes(term)
      );
    }
    if (only_new) models = models.filter((m) => !known.has(m.id));
    models.sort((a, b) => (b.created ?? 0) - (a.created ?? 0));
    const take = Math.min(Math.max(limit ?? 30, 1), 60);
    return ok({
      count: Math.min(models.length, take),
      total_matched: models.length,
      models: models.slice(0, take).map((m) => ({
        model_id: m.id,
        name: m.name,
        released: m.created ? new Date(m.created * 1e3).toISOString() : null,
        context_window: m.context_length ?? null,
        price_input: m.pricing?.prompt ? Number(m.pricing.prompt) : null,
        price_output: m.pricing?.completion ? Number(m.pricing.completion) : null,
        supports_reasoning: (m.supported_parameters ?? []).includes("reasoning"),
        already_curated: known.has(m.id)
      }))
    });
  }
});

// src/lib/mcp/tools/list-quick-prompts.ts
import { defineTool as defineTool11 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z9 } from "npm:zod@^4.5.4";
var list_quick_prompts_default = defineTool11({
  name: "list_quick_prompts",
  title: "List quick prompts",
  description: "List the suggested debate topics shown on the new-debate page. Admin callers also see disabled prompts.",
  inputSchema: {
    scenario_id: z9.string().optional().describe("Filter by scenario id.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ scenario_id }, ctx) => {
    const supabase = ctx.isAuthenticated() ? supabaseForUser(ctx) : supabaseAnon();
    let query = supabase.from("quick_prompts").select("id, topic, scenario_id, is_enabled, sort_order, updated_at").order("sort_order", { ascending: true });
    if (scenario_id) query = query.eq("scenario_id", scenario_id);
    const { data, error } = await query;
    if (error) return fail(error.message);
    return ok({ count: data?.length ?? 0, prompts: data ?? [] });
  }
});

// src/lib/mcp/tools/manage-quick-prompts.ts
import { defineTool as defineTool12 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z10 } from "npm:zod@^4.5.4";
var manage_quick_prompts_default = defineTool12({
  name: "manage_quick_prompts",
  title: "Manage quick prompts",
  description: "Admin only. Keep SiliconSoap's suggested debate topics fresh: add new prompts, enable/disable or delete existing ones, and reshuffle their display order.",
  inputSchema: {
    action: z10.enum(["add", "set_enabled", "delete", "shuffle"]).describe("What to do. 'shuffle' randomizes sort_order for all prompts."),
    topic: z10.string().optional().describe("For 'add': the prompt text."),
    scenario_id: z10.string().optional().describe("For 'add': scenario id. Defaults to 'general-problem'."),
    id: z10.string().optional().describe("Prompt id for 'set_enabled' and 'delete'."),
    is_enabled: z10.boolean().optional().describe("For 'set_enabled'.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ action, topic, scenario_id, id, is_enabled }, ctx) => {
    requireAuth(ctx);
    if (!await isAdmin(ctx)) return fail("Admin role required.");
    const supabase = supabaseForUser(ctx);
    return audited(
      ctx,
      {
        tool_name: "manage_quick_prompts",
        action,
        target_type: "quick_prompt",
        target_id: id ?? topic ?? null,
        input: { action, topic, scenario_id, id, is_enabled }
      },
      async () => {
        if (action === "add") {
          if (!topic?.trim()) return fail("`topic` is required for action 'add'.");
          const { data, error } = await supabase.from("quick_prompts").insert({
            topic: topic.trim(),
            scenario_id: scenario_id ?? "general-problem",
            is_enabled: true,
            sort_order: Math.floor(Math.random() * 1e3)
          }).select().maybeSingle();
          if (error) return fail(error.message);
          return ok({ action: "added", prompt: data });
        }
        if (action === "set_enabled") {
          if (!id) return fail("`id` is required.");
          if (is_enabled === void 0) return fail("`is_enabled` is required.");
          const { data, error } = await supabase.from("quick_prompts").update({ is_enabled }).eq("id", id).select().maybeSingle();
          if (error) return fail(error.message);
          if (!data) return fail("Prompt not found.");
          return ok({ action: "updated", prompt: data });
        }
        if (action === "delete") {
          if (!id) return fail("`id` is required.");
          const { error } = await supabase.from("quick_prompts").delete().eq("id", id);
          if (error) return fail(error.message);
          return ok({ action: "deleted", id });
        }
        const { data: prompts, error: readErr } = await supabase.from("quick_prompts").select("id");
        if (readErr) return fail(readErr.message);
        const ids = (prompts ?? []).map((p) => p.id);
        const order = ids.map((_, i) => i).sort(() => Math.random() - 0.5);
        let updated = 0;
        for (let i = 0; i < ids.length; i++) {
          const { error } = await supabase.from("quick_prompts").update({ sort_order: order[i] }).eq("id", ids[i]);
          if (!error) updated++;
        }
        return ok({ action: "shuffled", updated });
      }
    );
  }
});

// src/lib/mcp/tools/set-feature-flag.ts
import { defineTool as defineTool13 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z11 } from "npm:zod@^4.5.4";
var set_feature_flag_default = defineTool13({
  name: "set_feature_flag",
  title: "Set a feature flag",
  description: "Admin only. Update an existing SiliconSoap feature flag or configuration value (enabled state, text value, numeric value). This changes live platform behaviour immediately.",
  inputSchema: {
    key: z11.string().describe("Flag key from `list_feature_flags`, e.g. 'enable_judge_bot'."),
    enabled: z11.boolean().optional(),
    text_value: z11.string().optional().describe("For config flags such as 'default_judge_model'."),
    numeric_value: z11.number().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ key, enabled, text_value, numeric_value }, ctx) => {
    requireAuth(ctx);
    if (!await isAdmin(ctx)) return fail("Admin role required.");
    if (enabled === void 0 && text_value === void 0 && numeric_value === void 0) {
      return fail("Provide at least one of `enabled`, `text_value` or `numeric_value`.");
    }
    return audited(
      ctx,
      {
        tool_name: "set_feature_flag",
        action: "update",
        target_type: "feature_flag",
        target_id: key,
        input: { key, enabled, text_value, numeric_value }
      },
      async () => {
        const patch = { updated_at: (/* @__PURE__ */ new Date()).toISOString() };
        if (enabled !== void 0) patch.enabled = enabled;
        if (text_value !== void 0) patch.text_value = text_value;
        if (numeric_value !== void 0) patch.numeric_value = numeric_value;
        const { data, error } = await supabaseForUser(ctx).from("feature_flags").update(patch).eq("key", key).select("key, name, enabled, text_value, numeric_value").maybeSingle();
        if (error) return fail(error.message);
        if (!data) return fail(`No feature flag with key '${key}'.`);
        return ok({ flag: data });
      }
    );
  }
});

// src/lib/mcp/tools/site-stats.ts
import { defineTool as defineTool14 } from "npm:@lovable.dev/mcp-js@0.28.0";
var site_stats_default = defineTool14({
  name: "site_stats",
  title: "Site statistics",
  description: "Live SiliconSoap platform stats: public debate count, total views, model counts and the most viewed debates.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = supabaseAnon();
    const [{ count: debateCount, error: countErr }, viewsRes, modelsRes, topRes] = await Promise.all([
      supabase.from("agent_chats").select("id", { count: "exact", head: true }).eq("is_public", true).is("deleted_at", null),
      supabase.from("agent_chats").select("view_count, settings").eq("is_public", true).is("deleted_at", null),
      supabase.from("curated_models").select("model_id, is_enabled, supports_reasoning"),
      supabase.from("agent_chats").select("title, share_id, view_count").eq("is_public", true).is("deleted_at", null).order("view_count", { ascending: false }).limit(5)
    ]);
    if (countErr) return fail(countErr.message);
    if (viewsRes.error) return fail(viewsRes.error.message);
    const rows = viewsRes.data ?? [];
    const totalViews = rows.reduce((sum, r) => sum + (r.view_count ?? 0), 0);
    const totalAgents = rows.reduce((sum, r) => {
      const settings = r.settings ?? {};
      const n = Number(settings.agentCount ?? 2);
      return sum + (Number.isFinite(n) ? n : 2);
    }, 0);
    const models = modelsRes.data ?? [];
    return ok({
      public_debates: debateCount ?? 0,
      total_views: totalViews,
      agents_unleashed: totalAgents,
      models_total: models.length,
      models_enabled: models.filter((m) => m.is_enabled).length,
      models_with_reasoning: models.filter((m) => m.supports_reasoning).length,
      top_debates: (topRes.data ?? []).map((d) => ({
        title: d.title,
        views: d.view_count,
        url: d.share_id ? `https://siliconsoap.com/shared/${d.share_id}` : null
      }))
    });
  }
});

// src/lib/mcp/tools/sync-model-pricing.ts
import { defineTool as defineTool15 } from "npm:@lovable.dev/mcp-js@0.28.0";
var sync_model_pricing_default = defineTool15({
  name: "sync_model_pricing",
  title: "Sync model pricing & capabilities",
  description: "Admin only. Refresh pricing, context windows and reasoning support for every curated model from the live OpenRouter catalog.",
  inputSchema: {},
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: true },
  handler: async (_input, ctx) => {
    requireAuth(ctx);
    if (!await isAdmin(ctx)) return fail("Admin role required.");
    return audited(
      ctx,
      { tool_name: "sync_model_pricing", action: "sync", target_type: "curated_model" },
      async () => {
        const { status, body } = await invokeFunction(ctx, "sync-model-pricing", {
          method: "POST",
          body: {}
        });
        if (status >= 400) {
          const message = body?.error ?? `Pricing sync failed (${status}).`;
          return fail(message);
        }
        return ok(
          typeof body === "object" && body !== null ? body : { result: body }
        );
      }
    );
  }
});

// src/lib/mcp/tools/upsert-curated-model.ts
import { defineTool as defineTool16 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z12 } from "npm:zod@^4.5.4";
var upsert_curated_model_default = defineTool16({
  name: "upsert_curated_model",
  title: "Add or update a curated model",
  description: "Admin only. Add a new model to SiliconSoap's curated roster, or update an existing one (enabled state, reasoning toggle, metadata, pricing tier, sort order). Use `list_openrouter_models` first to get the exact model id.",
  inputSchema: {
    model_id: z12.string().describe("OpenRouter model id, e.g. 'anthropic/claude-sonnet-4.5'."),
    display_name: z12.string().optional().describe("Name shown in the UI. Required for new models."),
    provider: z12.string().optional().describe("Provider label. Required for new models."),
    description: z12.string().optional(),
    category: z12.string().optional(),
    license_type: z12.string().optional().describe("e.g. 'open-weights' or 'proprietary'."),
    speed_rating: z12.string().optional(),
    price_tier: z12.string().optional(),
    context_window: z12.number().int().optional(),
    is_free: z12.boolean().optional(),
    is_enabled: z12.boolean().optional().describe("Whether users can select this model."),
    supports_reasoning: z12.boolean().optional().describe("Whether the model supports reasoning at all (from OpenRouter)."),
    disable_reasoning: z12.boolean().optional().describe("Turn hidden thinking OFF for this model in debates."),
    sort_order: z12.number().int().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    requireAuth(ctx);
    if (!await isAdmin(ctx)) return fail("Admin role required.");
    const supabase = supabaseForUser(ctx);
    return audited(
      ctx,
      {
        tool_name: "upsert_curated_model",
        action: "upsert",
        target_type: "curated_model",
        target_id: input.model_id,
        input
      },
      async () => {
        const { data: existing, error: readErr } = await supabase.from("curated_models").select("id, model_id").eq("model_id", input.model_id).maybeSingle();
        if (readErr) return fail(readErr.message);
        const patch = {};
        for (const [key, value] of Object.entries(input)) {
          if (key !== "model_id" && value !== void 0) patch[key] = value;
        }
        if (existing) {
          const { data: data2, error: error2 } = await supabase.from("curated_models").update(patch).eq("id", existing.id).select().maybeSingle();
          if (error2) return fail(error2.message);
          return ok({ action: "updated", model: data2 });
        }
        if (!input.display_name || !input.provider) {
          return fail("New models require both `display_name` and `provider`.");
        }
        const { data, error } = await supabase.from("curated_models").insert({ model_id: input.model_id, ...patch }).select().maybeSingle();
        if (error) return fail(error.message);
        return ok({ action: "created", model: data });
      }
    );
  }
});

// src/lib/mcp/tools/whoami.ts
import { defineTool as defineTool17 } from "npm:@lovable.dev/mcp-js@0.28.0";
var whoami_default = defineTool17({
  name: "whoami",
  title: "Who am I",
  description: "Report the signed-in SiliconSoap identity behind this MCP connection: user id, email, display name, admin role and remaining credits.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return ok({ authenticated: false });
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [profileRes, creditsRes, admin] = await Promise.all([
      supabase.from("user_profiles").select("display_name").eq("user_id", userId).maybeSingle(),
      supabase.from("user_credits").select("credits_remaining, credits_used, tokens_used, token_budget").eq("user_id", userId).maybeSingle(),
      isAdmin(ctx)
    ]);
    if (profileRes.error) return fail(profileRes.error.message);
    return ok({
      authenticated: true,
      user_id: userId,
      email: ctx.getUserEmail(),
      display_name: profileRes.data?.display_name ?? null,
      is_admin: admin,
      credits: creditsRes.data ?? null,
      client_id: ctx.getClientId()
    });
  }
});

// src/lib/mcp/index.ts
var projectRef = "apfrjuomozdvdeondzaz";
var mcp_default = defineMcp({
  name: "siliconsoap",
  title: "siliconsoap",
  version: "1.0.0",
  instructions: [
    "SiliconSoap is a platform where multiple LLM agents debate a topic in rounds, soap-opera style.",
    "",
    "Read tools (no special role needed): `site_stats`, `list_models`, `list_debates`, `get_debate`,",
    "`list_quick_prompts`, `list_feature_flags`, `list_agent_profiles`, `list_hall_of_shame`,",
    "`list_my_debates`, `whoami`.",
    "",
    "Run a debate: `list_models` -> `create_debate` (costs 1 credit) -> poll `get_debate_status`",
    "until status is 'completed' -> `get_debate` for the transcript and share URL.",
    "",
    "Platform maintenance (admin role required): `list_openrouter_models` to discover newly",
    "released models, `upsert_curated_model` to add/update the roster, `sync_model_pricing` to",
    "refresh pricing and reasoning support, `manage_quick_prompts` to keep suggested topics fresh,",
    "and `set_feature_flag` to change live configuration (feature flags are the source of truth).",
    "Always read current state before writing, and report what you changed."
  ].join("\n"),
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    site_stats_default,
    list_models_default,
    list_debates_default,
    get_debate_default,
    list_quick_prompts_default,
    list_feature_flags_default,
    list_agent_profiles_default,
    list_hall_of_shame_default,
    whoami_default,
    list_my_debates_default,
    create_debate_default,
    get_debate_status_default,
    list_openrouter_models_default,
    upsert_curated_model_default,
    sync_model_pricing_default,
    manage_quick_prompts_default,
    set_feature_flag_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.28.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
